apiVersion: v1
kind: Service
metadata:
  labels: 
    app: maragatham-frontend
  namespace: batch2
  name: maragatham-frontend
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: maragatham-frontend 
  type: NodePort
